[db]
user = "colosseumdb_admin"
password = "pwd"
host = "localhost"
port = 5432
name = "colosseumdb"

[servers]

[servers.alpha]
url = "http://localhost:8001"
token = "password"

[files]
mb_limit = 10  # in megabytes
widget_ext = ['.html']
overview_ext = ['.md']
rules_ext = ['.md']
game_exec_ext = ['.zip', '.py', '.cpp', '.c']
submission_exec_ext = ['.zip', '.py', '.cpp', '.c']

[security]
login_timeout = 24  # in hours
submission_time_limit = 3  # in minutes