#!/usr/bin/env python3

from random import randint
import os


def generate_instances():
    path = os.path.abspath(os.getcwd())

    for size in range(50, 550, 50):
        file = open(path + '\\in\\136704_' + str(size) + '.txt', 'w')
        file.write(str(size) + '\n')

        machines = '1 '
        b = int(randint(80, 90)) / 100
        machines += str(b) + ' '
        b = int(randint(60, 80)) / 100
        machines += str(b) + ' '
        for i in range(2):
            b = int(randint(25, 60)) / 100
            machines += str(b) + ' '

        file.write(machines + '\n')

        for i in range(size):
            probability = randint(0, 100)
            if probability < 20:
                p = randint(1, 10)
                r = randint(int(size * 0.1), int(size * 0.2))
            elif probability < 40:
                p = randint(90, 100)
                r = randint(0, int(size * 0.1))
            else:
                p = randint(1, 100)
                r = randint(0, int(size))

            file.write(str(p) + ' ' + str(r) + '\n')
        file.close()


def generate_naive_solution(n):
    file = open('solutions/solution_' + str(n) + '.txt', 'w')
    line = ''
    previous_num = 0
    file.write('100\n')
    for i in range(n):
        num = int(i / (n / 5))
        if num != previous_num:
            file.write(line + '\n')
            line = str(i + 1) + ' '
            previous_num = num
        else:
            line += str(i + 1) + ' '
    file.write(line + '\n')
    file.close()


generate_naive_solution(50)
generate_instances()
